{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sharetarget",
    "module": "sharetarget",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sharetarget-1.2.0.aar",
          "url": "sharetarget-1.2.0.aar",
          "size": 32982,
          "sha512": "c65e6d88e3eea5df41725e0357692082a60ad8c2af67d7a69c09945766b82b6dc815466607d8ef8e56f9456b6cedde0cdeb917c49ac93b79974ba6f89f54c953",
          "sha256": "1d4e46d2c99b3ddf92163673cac212a4f0342ccf6827ff47606048b348ea78e3",
          "sha1": "d4809549c0fd00c541228ea7a80446b6686fd64f",
          "md5": "bd4b2e87f16b424efd115a3985670357"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sharetarget-1.2.0.aar",
          "url": "sharetarget-1.2.0.aar",
          "size": 32982,
          "sha512": "c65e6d88e3eea5df41725e0357692082a60ad8c2af67d7a69c09945766b82b6dc815466607d8ef8e56f9456b6cedde0cdeb917c49ac93b79974ba6f89f54c953",
          "sha256": "1d4e46d2c99b3ddf92163673cac212a4f0342ccf6827ff47606048b348ea78e3",
          "sha1": "d4809549c0fd00c541228ea7a80446b6686fd64f",
          "md5": "bd4b2e87f16b424efd115a3985670357"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sharetarget-1.2.0-sources.jar",
          "url": "sharetarget-1.2.0-sources.jar",
          "size": 13297,
          "sha512": "045567b02987d3161a46d042f71e40bfd1e6c15ad7fee56237b74bb36f3908aa7f6f47f71d126f4f5c50dca7a1ba9f6f27a43eba03c18d6ded03ccab9dae399a",
          "sha256": "4893309311e53712084d106e803d0a8196b7c4b74a255ea69e12ae80f20cfe5c",
          "sha1": "057697c99824a7620c75420e6fd6c8a752e6fd61",
          "md5": "c387a7419a9ec4dba8c0e6858fc0c3cd"
        }
      ]
    }
  ]
}